export const QUOTATION_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  EXPIRED: 'EXPIRED'
};

export const ITEM_AVAILABILITY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  PARTIAL: 'PARTIAL',
  UNAVAILABLE: 'UNAVAILABLE'
};

export const QUOTATION_COMPLETENESS = {
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  UNAVAILABLE: 'UNAVAILABLE'
};

export const STATUS_COLORS = {
  [QUOTATION_STATUS.DRAFT]: 'bg-gray-100 text-gray-800',
  [QUOTATION_STATUS.SUBMITTED]: 'bg-blue-100 text-blue-800',
  [QUOTATION_STATUS.ACCEPTED]: 'bg-green-100 text-green-800',
  [QUOTATION_STATUS.DECLINED]: 'bg-red-100 text-red-800',
  [QUOTATION_STATUS.EXPIRED]: 'bg-yellow-100 text-yellow-800',
  [ITEM_AVAILABILITY_STATUS.AVAILABLE]: 'text-green-600',
  [ITEM_AVAILABILITY_STATUS.PARTIAL]: 'text-yellow-600',
  [ITEM_AVAILABILITY_STATUS.UNAVAILABLE]: 'text-red-600'
};
