import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import dashboardService from '../../features/dashboards/dashboardService';
import StatCard from '../../components/dashboard/StatCard';
import DashboardSection from '../../components/dashboard/DashboardSection';
import StatusChart from '../../components/dashboard/StatusChart';
import TrendChart from '../../components/dashboard/TrendChart';
import { Inbox, FileSignature, ShoppingBag, CheckCircle, DollarSign, Clock, Store, Download } from 'lucide-react';
import { Card, CardContent } from '../../components/ui/Card';
import StatusBadge from '../../components/ui/StatusBadge';
import Skeleton from '../../components/ui/Skeleton';
import EmptyState from '../../components/ui/EmptyState';
import Button from '../../components/ui/Button';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const PharmacyDashboardPage = () => {
  const { user } = useAuth();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [range, setRange] = useState('30d');

  // Report Generation State
  const [isReportModalOpen, setIsReportModalOpen] = useState(false);
  const [reportStartDate, setReportStartDate] = useState('');
  const [reportEndDate, setReportEndDate] = useState('');
  const [reportLoading, setReportLoading] = useState(false);
  const [reportError, setReportError] = useState('');

  useEffect(() => {
    const fetchDashboard = async () => {
      setLoading(true);
      try {
        const result = await dashboardService.getPharmacyDashboard({ range });
        setData(result.data);
      } catch (error) {
        console.error('Failed to fetch dashboard', error);
      } finally {
        setLoading(false);
      }
    };
    fetchDashboard();
  }, [range]);

  const handleRangeChange = (e) => {
    setRange(e.target.value);
  };

  const handleGenerateReport = async () => {
    if (!reportStartDate || !reportEndDate) {
      setReportError('Please select both start and end dates.');
      return;
    }
    try {
      setReportLoading(true);
      setReportError('');
      const response = await dashboardService.generatePharmacyReport(reportStartDate, reportEndDate);
      const reportData = response.data || [];

      const doc = new jsPDF();

      // Add Pharmacy Logo / Name
      doc.setFontSize(22);
      doc.setTextColor(11, 19, 84); // #0B1354
      doc.text(user?.pharmacy?.name || 'Pharmacy', 14, 22);

      // Add Report Title
      doc.setFontSize(14);
      doc.setTextColor(100);
      doc.text('Sales & Orders Report', 14, 30);

      // Date Range
      doc.setFontSize(10);
      doc.text(`Period: ${reportStartDate} to ${reportEndDate}`, 14, 36);

      if (!reportData || reportData.length === 0) {
        doc.text('No sales data found for the selected period.', 14, 50);
      } else {
        // Summary Stats
        const totalSales = reportData.reduce((acc, order) => acc + parseFloat(order.total || 0), 0);
        const completedOrders = reportData.filter(o => o.orderStatus === 'COMPLETED').length;

        doc.setFillColor(248, 250, 252);
        doc.rect(14, 42, 182, 20, 'F');
        doc.setFontSize(10);
        doc.setTextColor(11, 19, 84);
        doc.text(`Total Orders: ${reportData.length}`, 18, 49);
        doc.text(`Completed Orders: ${completedOrders}`, 18, 56);
        doc.text(`Total Revenue: Rs. ${totalSales.toFixed(2)}`, 110, 49);
        doc.text(`Average Order Value: Rs. ${(totalSales / reportData.length).toFixed(2)}`, 110, 56);

        // Table
        const tableColumn = ["Order #", "Date", "Customer", "Payment", "Status", "Total (Rs)"];
        const tableRows = [];

        reportData.forEach(order => {
          tableRows.push([
            order.orderNumber,
            order.date,
            order.customerName,
            order.paymentMethod,
            order.orderStatus,
            order.total
          ]);
        });

        autoTable(doc, {
          head: [tableColumn],
          body: tableRows,
          startY: 68,
          theme: 'grid',
          styles: { fontSize: 9, cellPadding: 3 },
          headStyles: { fillColor: [11, 19, 84], textColor: 255 },
          alternateRowStyles: { fillColor: [248, 250, 252] },
          columnStyles: {
            5: { halign: 'right', fontStyle: 'bold' } // Total column
          }
        });

        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
          doc.setPage(i);
          doc.setFontSize(8);
          doc.setTextColor(150);
          doc.text(`Generated by CureLink on ${new Date().toLocaleString()}`, 14, doc.internal.pageSize.height - 10);
          doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
        }
      }

      doc.save(`pharmacy_sales_report_${reportStartDate}_to_${reportEndDate}.pdf`);
      setIsReportModalOpen(false);
    } catch (err) {
      console.error(err);
      setReportError('Failed to generate report. Please try again.');
    } finally {
      setReportLoading(false);
    }
  };

  if (loading && !data) {
    return (
      <div className="mx-auto px-4 py-8 max-w-7xl">
        <Skeleton className="h-10 w-64 mb-2" />
        <Skeleton className="h-5 w-48 mb-8" />
        <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-8">
          {[1, 2, 3, 4, 5, 6].map(i => <Skeleton key={i} className="h-32 w-full rounded-xl" />)}
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <Skeleton className="h-64 w-full rounded-xl" />
          <Skeleton className="h-64 w-full rounded-xl" />
        </div>
      </div>
    );
  }

  return (
    <div className="animate-in fade-in duration-500 bg-slate-50 min-h-screen">
      {/* Modern Header Section */}
      <div className="bg-[#0B1354] pb-24 pt-8 px-4 sm:px-6 lg:px-8 relative overflow-hidden rounded-b-[3rem] mb-[-4rem]">
        <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '32px 32px' }}></div>
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary-500 rounded-full mix-blend-screen filter blur-[80px] opacity-30 animate-pulse"></div>

        <div className="max-w-7xl mx-auto relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-white tracking-tight">Pharmacy Dashboard</h1>
            <p className="mt-2 text-blue-100 font-medium">Overview for {user?.pharmacy?.name || 'your pharmacy'}</p>
          </div>
          <div className="flex flex-col sm:flex-row items-center gap-4">
            <Button
              variant="outline"
              size="sm"
              icon={Download}
              onClick={() => setIsReportModalOpen(true)}
              className="bg-white/10 text-white border-white/20 hover:bg-white/20 w-full sm:w-auto"
            >
              Generate Report
            </Button>
            <div className="flex items-center bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-1.5 shadow-lg">
              <label htmlFor="range" className="text-sm font-medium text-blue-50 mx-4">Time Range:</label>
              <select
                id="range"
                value={range}
                onChange={handleRangeChange}
                className="bg-white rounded-xl text-sm font-bold text-slate-900 focus:ring-2 focus:ring-[#0B1354] cursor-pointer py-2 pl-4 pr-10 outline-none hover:bg-slate-50 transition-colors shadow-sm"
              >
                <option value="7d">Last 7 Days</option>
                <option value="30d">Last 30 Days</option>
                <option value="90d">Last 90 Days</option>
              </select>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-12 relative z-20">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-5 mb-10">
          <StatCard
            title="Incoming Requests"
            value={data?.summary?.incomingRequests || 0}
            icon={Inbox}
            colorClass="text-[#0B1354] bg-[#0B1354]/10"
            linkUrl="/pharmacy/inbox"
          />
          <StatCard
            title="Active Quotes"
            value={data?.summary?.submittedQuotations || 0}
            icon={FileSignature}
            colorClass="text-[#0B1354] bg-[#0B1354]/10"
          />
          <StatCard
            title="Active Orders"
            value={data?.summary?.activeOrders || 0}
            icon={ShoppingBag}
            colorClass="text-amber-600 bg-amber-100"
            linkUrl="/pharmacy/orders"
          />
          <StatCard
            title="Completed Orders"
            value={data?.summary?.completedOrders || 0}
            icon={CheckCircle}
            colorClass="text-emerald-600 bg-emerald-100"
          />
          <StatCard
            title="Gross Value (LKR)"
            value={(data?.summary?.grossFulfilledOrderValue || 0).toLocaleString()}
            icon={DollarSign}
            colorClass="text-emerald-600 bg-emerald-100"
          />
          <StatCard
            title="Avg Response (Min)"
            value={data?.summary?.averageResponseMinutes || '-'}
            icon={Clock}
            colorClass="text-[#0B1354] bg-[#0B1354]/10"
          />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-10">
          <DashboardSection title="Order Fulfillment Value">
            <Card>
              <CardContent className="p-6">
                <TrendChart data={data?.charts?.fulfilledValueTrend} color="#10b981" />
              </CardContent>
            </Card>
          </DashboardSection>
          <DashboardSection title="Orders by Status">
            <Card>
              <CardContent className="p-6">
                <StatusChart data={data?.charts?.ordersByStatus} />
              </CardContent>
            </Card>
          </DashboardSection>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          <DashboardSection title="Recent Incoming Requests">
            <Card className="bg-white/80 backdrop-blur-xl border border-white/50 shadow-xl rounded-3xl overflow-hidden">
              {data?.incomingRequests?.length > 0 ? (
                <ul className="divide-y divide-slate-100">
                  {data.incomingRequests.map(req => {
                    const expiresAt = req.expiresAt ? new Date(req.expiresAt) : null;
                    const hoursLeft = expiresAt ? Math.max(0, Math.round((expiresAt - Date.now()) / 3600000)) : null;
                    const isUrgent = hoursLeft !== null && hoursLeft <= 3;
                    return (
                      <li
                        key={req.id}
                        className="p-5 hover:bg-slate-50 transition-colors flex justify-between items-center group cursor-pointer"
                        onClick={() => window.location.href = `/pharmacy/requests/${req.id}`}
                      >
                        <div className="flex items-center gap-4">
                          <div className={`w-10 h-10 rounded-full flex items-center justify-center group-hover:scale-110 transition-transform ${isUrgent ? 'bg-rose-50 text-rose-600' : 'bg-blue-50 text-blue-600'}`}>
                            <Inbox className="w-5 h-5" />
                          </div>
                          <div>
                            <span className="font-bold text-slate-900 group-hover:text-[#0B1354] transition-colors text-base">
                              #{req.requestNumber}
                            </span>
                            <div className="flex flex-wrap items-center gap-2 mt-1">
                              <span className="text-xs text-slate-500 font-medium">{req.medicineCount} item{req.medicineCount !== 1 ? 's' : ''}</span>
                              {req.requiresPrescription && (
                                <span className="text-[10px] font-bold bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full uppercase tracking-wide">Rx</span>
                              )}
                              {expiresAt && (
                                <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wide ${
                                  isUrgent ? 'bg-rose-100 text-rose-700' : 'bg-slate-100 text-slate-600'
                                }`}>
                                  {hoursLeft === 0 ? 'Expiring soon' : `${hoursLeft}h left`}
                                </span>
                              )}
                            </div>
                          </div>
                        </div>
                        <div className="text-right shrink-0">
                          <span className="text-xs text-slate-400 font-medium">{new Date(req.submittedAt).toLocaleDateString()}</span>
                          <div className="mt-1 text-xs font-semibold text-[#0B1354] group-hover:underline">View →</div>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              ) : (
                <EmptyState
                  icon={Inbox}
                  title="Inbox is empty"
                  description="No recent requests from customers."
                />
              )}
            </Card>
          </DashboardSection>

          <DashboardSection title="Active Orders To Prepare">
            <Card className="bg-white/80 backdrop-blur-xl border border-white/50 shadow-xl rounded-3xl overflow-hidden">
              {data?.activeOrders?.length > 0 ? (
                <ul className="divide-y divide-slate-100">
                  {data.activeOrders.map(order => {
                    const fulfilLabel = order.fulfilmentMethod === 'DELIVERY' ? '🚚 Delivery' : order.fulfilmentMethod === 'PICKUP' ? '🏪 Pickup' : order.fulfilmentMethod;
                    return (
                      <li
                        key={order.id}
                        className="p-5 hover:bg-slate-50 transition-colors flex justify-between items-center group cursor-pointer"
                        onClick={() => window.location.href = `/pharmacy/orders/${order.id}`}
                      >
                        <div className="flex items-center gap-4">
                          <div className="w-10 h-10 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center group-hover:scale-110 transition-transform">
                            <ShoppingBag className="w-5 h-5" />
                          </div>
                          <div>
                            <span className="font-bold text-slate-900 group-hover:text-emerald-700 transition-colors text-base">
                              #{order.orderNumber}
                            </span>
                            <div className="flex flex-wrap items-center gap-2 mt-1">
                              <span className="text-xs text-slate-500 font-medium">{order.safeCustomerName}</span>
                              {fulfilLabel && (
                                <span className="text-[10px] font-bold bg-slate-100 text-slate-600 px-2 py-0.5 rounded-full">{fulfilLabel}</span>
                              )}
                              {order.total > 0 && (
                                <span className="text-[10px] font-bold bg-emerald-50 text-emerald-700 px-2 py-0.5 rounded-full">Rs. {order.total.toFixed(2)}</span>
                              )}
                            </div>
                          </div>
                        </div>
                        <div className="text-right shrink-0">
                          <StatusBadge status={order.orderStatus} />
                          <div className="mt-1 text-xs font-semibold text-emerald-700 group-hover:underline">View →</div>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              ) : (
                <EmptyState
                  icon={ShoppingBag}
                  title="All caught up"
                  description="No active orders needing attention right now."
                />
              )}
            </Card>
          </DashboardSection>
        </div>
      </div>

      {/* Report Generation Modal */}
      {isReportModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/50 backdrop-blur-sm">
          <div className="bg-white rounded-3xl shadow-2xl max-w-md w-full p-6 animate-in zoom-in-95 duration-200">
            <div className="flex justify-between items-center mb-6">
              <h3 className="text-xl font-bold text-[#0B1354]">Generate Sales Report</h3>
              <button
                onClick={() => setIsReportModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 transition-colors"
              >
                ✕
              </button>
            </div>

            {reportError && (
              <div className="mb-4 p-3 bg-red-50 text-red-600 rounded-xl text-sm font-medium border border-red-100">
                {reportError}
              </div>
            )}

            <div className="space-y-4">
              <div>
                <label className="block text-sm font-bold text-slate-700 mb-1">Start Date</label>
                <input
                  type="date"
                  value={reportStartDate}
                  onChange={(e) => setReportStartDate(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2 text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#0B1354]"
                />
              </div>
              <div>
                <label className="block text-sm font-bold text-slate-700 mb-1">End Date</label>
                <input
                  type="date"
                  value={reportEndDate}
                  onChange={(e) => setReportEndDate(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-xl px-4 py-2 text-slate-900 focus:outline-none focus:ring-2 focus:ring-[#0B1354]"
                />
              </div>
            </div>

            <div className="mt-8 flex justify-end gap-3">
              <Button
                variant="outline"
                onClick={() => setIsReportModalOpen(false)}
              >
                Cancel
              </Button>
              <Button
                onClick={handleGenerateReport}
                disabled={reportLoading}
                className="bg-[#0B1354] text-white hover:bg-[#0B1354]/90"
              >
                {reportLoading ? 'Generating...' : 'Download PDF'}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default PharmacyDashboardPage;
