require('dotenv').config();
const mongoose = require('mongoose');
const Medicine = require('../modules/medicines/medicine.model');
const User = require('../modules/users/user.model');

const sampleMedicines = [
  {
    name: 'Panadol',
    brand: 'GSK',
    dosage: '500mg',
    category: 'Pain Relief',
    description: 'Paracetamol 500mg tablets for effective pain relief and fever reduction.',
    prescriptionRequired: false,
    manufacturer: 'GlaxoSmithKline',
  },
  {
    name: 'Panadol',
    brand: 'GSK',
    dosage: 'Syrup 120mg/5ml',
    category: 'Pain Relief',
    description: 'Paracetamol syrup for children.',
    prescriptionRequired: false,
    manufacturer: 'GlaxoSmithKline',
  },
  {
    name: 'Paracetamol',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Pain Relief',
    description: 'Paracetamol 500mg tablets.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Paracetamol',
    brand: 'Generic',
    dosage: '650mg',
    category: 'Pain Relief',
    description: 'Paracetamol 650mg tablets for severe pain.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Loratadine',
    brand: 'Claritin',
    dosage: '10mg',
    category: 'Allergy',
    description: 'Antihistamine used to treat allergies.',
    prescriptionRequired: false,
    manufacturer: 'Bayer',
  },
  {
    name: 'Amoxicillin',
    brand: 'Amoxil',
    dosage: '250mg',
    category: 'Antibiotics',
    description: 'Penicillin antibiotic used to treat various bacterial infections.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Amoxicillin',
    brand: 'Amoxil',
    dosage: '500mg',
    category: 'Antibiotics',
    description: 'Penicillin antibiotic used to treat various bacterial infections.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Amoxicillin',
    brand: 'Amoxil',
    dosage: 'Syrup 125mg/5ml',
    category: 'Antibiotics',
    description: 'Penicillin antibiotic syrup.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Lisinopril',
    brand: 'Prinivil',
    dosage: '10mg',
    category: 'Cardiovascular',
    description: 'ACE inhibitor used to treat high blood pressure and heart failure.',
    prescriptionRequired: true,
    manufacturer: 'Merck',
  },
  {
    name: 'Lisinopril',
    brand: 'Prinivil',
    dosage: '20mg',
    category: 'Cardiovascular',
    description: 'ACE inhibitor used to treat high blood pressure and heart failure.',
    prescriptionRequired: true,
    manufacturer: 'Merck',
  },
  {
    name: 'Ibuprofen',
    brand: 'Advil',
    dosage: '200mg',
    category: 'Pain Relief',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID).',
    prescriptionRequired: false,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Ibuprofen',
    brand: 'Advil',
    dosage: '400mg',
    category: 'Pain Relief',
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) used for pain and inflammation.',
    prescriptionRequired: false,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Cetirizine',
    brand: 'Zyrtec',
    dosage: '10mg',
    category: 'Allergy',
    description: 'Antihistamine used to relieve allergy symptoms like watery eyes, runny nose, and sneezing.',
    prescriptionRequired: false,
    manufacturer: 'Johnson & Johnson',
  },
  {
    name: 'Cetirizine',
    brand: 'Zyrtec',
    dosage: 'Syrup 5mg/5ml',
    category: 'Allergy',
    description: 'Antihistamine syrup for children.',
    prescriptionRequired: false,
    manufacturer: 'Johnson & Johnson',
  },
  {
    name: 'Metformin',
    brand: 'Glucophage',
    dosage: '500mg',
    category: 'Diabetes',
    description: 'First-line medication for the treatment of type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Bristol-Myers Squibb',
  },
  {
    name: 'Metformin',
    brand: 'Glucophage',
    dosage: '850mg',
    category: 'Diabetes',
    description: 'First-line medication for the treatment of type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Bristol-Myers Squibb',
  },
  {
    name: 'Omeprazole',
    brand: 'Prilosec',
    dosage: '20mg',
    category: 'Gastrointestinal',
    description: 'Proton pump inhibitor (PPI) that decreases stomach acid production.',
    prescriptionRequired: false,
    manufacturer: 'AstraZeneca',
  },
  {
    name: 'Omeprazole',
    brand: 'Prilosec',
    dosage: '40mg',
    category: 'Gastrointestinal',
    description: 'Proton pump inhibitor (PPI) that decreases stomach acid production.',
    prescriptionRequired: false,
    manufacturer: 'AstraZeneca',
  },
  {
    name: 'Atorvastatin',
    brand: 'Lipitor',
    dosage: '10mg',
    category: 'Cardiovascular',
    description: 'Statin medication used to prevent cardiovascular disease and lower lipid levels.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Atorvastatin',
    brand: 'Lipitor',
    dosage: '20mg',
    category: 'Cardiovascular',
    description: 'Statin medication used to prevent cardiovascular disease and lower lipid levels.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Salbutamol',
    brand: 'Ventolin',
    dosage: '100mcg',
    category: 'Respiratory',
    description: 'Inhaler used for the relief of asthma and COPD symptoms.',
    prescriptionRequired: true,
    manufacturer: 'GlaxoSmithKline',
  },
  {
    name: 'Aspirin',
    brand: 'Bayer',
    dosage: '75mg',
    category: 'Pain Relief',
    description: 'Used to reduce pain, fever, or inflammation.',
    prescriptionRequired: false,
    manufacturer: 'Bayer AG',
  },
  {
    name: 'Aspirin',
    brand: 'Bayer',
    dosage: '150mg',
    category: 'Pain Relief',
    description: 'Used to reduce pain, fever, or inflammation.',
    prescriptionRequired: false,
    manufacturer: 'Bayer AG',
  },
  {
    name: 'Piriton',
    brand: 'Piriton',
    dosage: '4mg',
    category: 'Allergy',
    description: 'Chlorphenamine maleate used for hayfever and allergy relief.',
    prescriptionRequired: false,
    manufacturer: 'GSK',
  },
  {
    name: 'Amoxil',
    brand: 'Amoxil',
    dosage: '250mg',
    category: 'Antibiotics',
    description: 'Broad spectrum penicillin antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Augmentin',
    brand: 'Augmentin',
    dosage: '375mg',
    category: 'Antibiotics',
    description: 'Co-amoxiclav used for treating bacterial infections.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Zithromax',
    brand: 'Zithromax',
    dosage: '250mg',
    category: 'Antibiotics',
    description: 'Azithromycin antibiotic for respiratory and skin infections.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Losar',
    brand: 'Losar',
    dosage: '50mg',
    category: 'Cardiovascular',
    description: 'Losartan potassium used for high blood pressure.',
    prescriptionRequired: true,
    manufacturer: 'Torrent Pharma',
  },
  {
    name: 'Amloc',
    brand: 'Amloc',
    dosage: '5mg',
    category: 'Cardiovascular',
    description: 'Amlodipine tablet for treating hypertension.',
    prescriptionRequired: true,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Concor',
    brand: 'Concor',
    dosage: '5mg',
    category: 'Cardiovascular',
    description: 'Bisoprolol fumarate used for heart failure and hypertension.',
    prescriptionRequired: true,
    manufacturer: 'Merck',
  },
  {
    name: 'Ecosprin',
    brand: 'Ecosprin',
    dosage: '75mg',
    category: 'Cardiovascular',
    description: 'Low dose aspirin used to prevent heart attacks.',
    prescriptionRequired: false,
    manufacturer: 'USV',
  },
  {
    name: 'Diamicron',
    brand: 'Diamicron',
    dosage: '60mg',
    category: 'Diabetes',
    description: 'Gliclazide used for controlling blood sugar in type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Servier',
  },
  {
    name: 'Januvia',
    brand: 'Januvia',
    dosage: '50mg',
    category: 'Diabetes',
    description: 'Sitagliptin used for type 2 diabetes management.',
    prescriptionRequired: true,
    manufacturer: 'Merck',
  },
  {
    name: 'Jardiance',
    brand: 'Jardiance',
    dosage: '10mg',
    category: 'Diabetes',
    description: 'Empagliflozin used to treat type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Boehringer Ingelheim',
  },
  {
    name: 'Digene',
    brand: 'Digene',
    dosage: 'Tablet',
    category: 'Gastrointestinal',
    description: 'Antacid used for relieving acidity and gas.',
    prescriptionRequired: false,
    manufacturer: 'Abbott',
  },
  {
    name: 'Gelusil',
    brand: 'Gelusil',
    dosage: 'Syrup',
    category: 'Gastrointestinal',
    description: 'Antacid liquid for heartburn and indigestion.',
    prescriptionRequired: false,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Domstal',
    brand: 'Domstal',
    dosage: '10mg',
    category: 'Gastrointestinal',
    description: 'Domperidone used for nausea and vomiting.',
    prescriptionRequired: false,
    manufacturer: 'Torrent Pharma',
  },
  {
    name: 'Nexium',
    brand: 'Nexium',
    dosage: '20mg',
    category: 'Gastrointestinal',
    description: 'Esomeprazole used for acid reflux.',
    prescriptionRequired: true,
    manufacturer: 'AstraZeneca',
  },
  {
    name: 'Imodium',
    brand: 'Imodium',
    dosage: '2mg',
    category: 'Gastrointestinal',
    description: 'Loperamide used for treating diarrhea.',
    prescriptionRequired: false,
    manufacturer: 'Johnson & Johnson',
  },
  {
    name: 'Singulair',
    brand: 'Singulair',
    dosage: '10mg',
    category: 'Respiratory',
    description: 'Montelukast used for asthma and allergies.',
    prescriptionRequired: true,
    manufacturer: 'Merck',
  },
  {
    name: 'Flixotide',
    brand: 'Flixotide',
    dosage: '125mcg',
    category: 'Respiratory',
    description: 'Fluticasone inhaler for asthma management.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Seretide',
    brand: 'Seretide',
    dosage: '250mcg',
    category: 'Respiratory',
    description: 'Combination inhaler for asthma and COPD.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Telfast',
    brand: 'Telfast',
    dosage: '120mg',
    category: 'Allergy',
    description: 'Fexofenadine used for allergy relief.',
    prescriptionRequired: false,
    manufacturer: 'Sanofi',
  },
  {
    name: 'Vitamin C',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Vitamins',
    description: 'Ascorbic acid supplement for immunity.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Neurobion',
    brand: 'Neurobion',
    dosage: 'Forte',
    category: 'Vitamins',
    description: 'Vitamin B complex supplement.',
    prescriptionRequired: false,
    manufacturer: 'Merck',
  },
  {
    name: 'Caltrate',
    brand: 'Caltrate',
    dosage: '600mg',
    category: 'Vitamins',
    description: 'Calcium and Vitamin D3 supplement.',
    prescriptionRequired: false,
    manufacturer: 'Pfizer',
  },
  {
    name: 'Centrum',
    brand: 'Centrum',
    dosage: 'Adult',
    category: 'Vitamins',
    description: 'Daily multivitamin supplement.',
    prescriptionRequired: false,
    manufacturer: 'GSK',
  },
  {
    name: 'Betnovate',
    brand: 'Betnovate',
    dosage: '0.1%',
    category: 'Dermatology',
    description: 'Betamethasone cream for skin inflammation.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Canesten',
    brand: 'Canesten',
    dosage: '1%',
    category: 'Dermatology',
    description: 'Clotrimazole cream for fungal infections.',
    prescriptionRequired: false,
    manufacturer: 'Bayer',
  },
  {
    name: 'Voltaren',
    brand: 'Voltaren',
    dosage: '1%',
    category: 'Pain Relief',
    description: 'Diclofenac gel for muscle and joint pain.',
    prescriptionRequired: false,
    manufacturer: 'Novartis',
  },
  {
    name: 'Thyrox',
    brand: 'Thyrox',
    dosage: '50mcg',
    category: 'Endocrine',
    description: 'Levothyroxine for hypothyroidism.',
    prescriptionRequired: true,
    manufacturer: 'MacLeod',
  },
  {
    name: 'Eltroxin',
    brand: 'Eltroxin',
    dosage: '50mcg',
    category: 'Endocrine',
    description: 'Levothyroxine sodium tablets.',
    prescriptionRequired: true,
    manufacturer: 'GSK',
  },
  {
    name: 'Azithromycin',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Antibiotics',
    description: 'Macrolide antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Ciprofloxacin',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Antibiotics',
    description: 'Fluoroquinolone antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Doxycycline',
    brand: 'Generic',
    dosage: '100mg',
    category: 'Antibiotics',
    description: 'Tetracycline antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Cephalexin',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Antibiotics',
    description: 'Cephalosporin antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Metronidazole',
    brand: 'Generic',
    dosage: '400mg',
    category: 'Antibiotics',
    description: 'Antibiotic and antiprotozoal.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Clindamycin',
    brand: 'Generic',
    dosage: '300mg',
    category: 'Antibiotics',
    description: 'Lincosamide antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Levofloxacin',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Antibiotics',
    description: 'Fluoroquinolone antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Rosuvastatin',
    brand: 'Generic',
    dosage: '10mg',
    category: 'Cardiovascular',
    description: 'Statin for lowering cholesterol.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Simvastatin',
    brand: 'Generic',
    dosage: '20mg',
    category: 'Cardiovascular',
    description: 'Statin for lowering cholesterol.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Valsartan',
    brand: 'Generic',
    dosage: '80mg',
    category: 'Cardiovascular',
    description: 'Angiotensin II receptor blocker.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Enalapril',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Cardiovascular',
    description: 'ACE inhibitor.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Ramipril',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Cardiovascular',
    description: 'ACE inhibitor.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Atenolol',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Cardiovascular',
    description: 'Beta blocker.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Metoprolol',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Cardiovascular',
    description: 'Beta blocker.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Carvedilol',
    brand: 'Generic',
    dosage: '6.25mg',
    category: 'Cardiovascular',
    description: 'Beta blocker.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Furosemide',
    brand: 'Generic',
    dosage: '40mg',
    category: 'Cardiovascular',
    description: 'Loop diuretic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Spironolactone',
    brand: 'Generic',
    dosage: '25mg',
    category: 'Cardiovascular',
    description: 'Potassium-sparing diuretic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Glimepiride',
    brand: 'Generic',
    dosage: '2mg',
    category: 'Diabetes',
    description: 'Sulfonylurea for type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Glipizide',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Diabetes',
    description: 'Sulfonylurea for type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Pioglitazone',
    brand: 'Generic',
    dosage: '15mg',
    category: 'Diabetes',
    description: 'Thiazolidinedione for type 2 diabetes.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Insulin Glargine',
    brand: 'Generic',
    dosage: '100 IU/mL',
    category: 'Diabetes',
    description: 'Long-acting insulin.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Insulin Aspart',
    brand: 'Generic',
    dosage: '100 IU/mL',
    category: 'Diabetes',
    description: 'Rapid-acting insulin.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Pantoprazole',
    brand: 'Generic',
    dosage: '40mg',
    category: 'Gastrointestinal',
    description: 'Proton pump inhibitor.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Lansoprazole',
    brand: 'Generic',
    dosage: '30mg',
    category: 'Gastrointestinal',
    description: 'Proton pump inhibitor.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Famotidine',
    brand: 'Generic',
    dosage: '20mg',
    category: 'Gastrointestinal',
    description: 'H2 blocker for acidity.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Ranitidine',
    brand: 'Generic',
    dosage: '150mg',
    category: 'Gastrointestinal',
    description: 'H2 blocker for acidity.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Mebeverine',
    brand: 'Generic',
    dosage: '135mg',
    category: 'Gastrointestinal',
    description: 'Antispasmodic for IBS.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Ondansetron',
    brand: 'Generic',
    dosage: '4mg',
    category: 'Gastrointestinal',
    description: 'Antiemetic for nausea.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Budesonide',
    brand: 'Generic',
    dosage: '200mcg',
    category: 'Respiratory',
    description: 'Corticosteroid for asthma.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Formoterol',
    brand: 'Generic',
    dosage: '12mcg',
    category: 'Respiratory',
    description: 'Long-acting beta agonist.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Tiotropium',
    brand: 'Generic',
    dosage: '18mcg',
    category: 'Respiratory',
    description: 'Anticholinergic for COPD.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Ipratropium',
    brand: 'Generic',
    dosage: '20mcg',
    category: 'Respiratory',
    description: 'Bronchodilator.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Levocetirizine',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Allergy',
    description: 'Antihistamine.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Desloratadine',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Allergy',
    description: 'Antihistamine.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Chlorpheniramine',
    brand: 'Generic',
    dosage: '4mg',
    category: 'Allergy',
    description: 'Antihistamine.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Folic Acid',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Vitamins',
    description: 'Vitamin B9 supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Vitamin D3',
    brand: 'Generic',
    dosage: '1000 IU',
    category: 'Vitamins',
    description: 'Cholecalciferol supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Vitamin E',
    brand: 'Generic',
    dosage: '400 IU',
    category: 'Vitamins',
    description: 'Antioxidant vitamin.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Zinc',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Vitamins',
    description: 'Mineral supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Iron',
    brand: 'Generic',
    dosage: '200mg',
    category: 'Vitamins',
    description: 'Ferrous sulfate supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Calcium',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Vitamins',
    description: 'Calcium carbonate supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Magnesium',
    brand: 'Generic',
    dosage: '250mg',
    category: 'Vitamins',
    description: 'Mineral supplement.',
    prescriptionRequired: false,
    manufacturer: 'Generic',
  },
  {
    name: 'Ketoconazole',
    brand: 'Generic',
    dosage: '2%',
    category: 'Dermatology',
    description: 'Antifungal.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Mupirocin',
    brand: 'Generic',
    dosage: '2%',
    category: 'Dermatology',
    description: 'Topical antibiotic.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Isotretinoin',
    brand: 'Generic',
    dosage: '20mg',
    category: 'Dermatology',
    description: 'Treatment for severe acne.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Sertraline',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Psychiatry',
    description: 'SSRI antidepressant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Escitalopram',
    brand: 'Generic',
    dosage: '10mg',
    category: 'Psychiatry',
    description: 'SSRI antidepressant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Fluoxetine',
    brand: 'Generic',
    dosage: '20mg',
    category: 'Psychiatry',
    description: 'SSRI antidepressant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Alprazolam',
    brand: 'Generic',
    dosage: '0.5mg',
    category: 'Psychiatry',
    description: 'Benzodiazepine for anxiety.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Clonazepam',
    brand: 'Generic',
    dosage: '0.5mg',
    category: 'Psychiatry',
    description: 'Benzodiazepine.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Diazepam',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Psychiatry',
    description: 'Benzodiazepine.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Zolpidem',
    brand: 'Generic',
    dosage: '10mg',
    category: 'Psychiatry',
    description: 'Sedative for insomnia.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Gabapentin',
    brand: 'Generic',
    dosage: '300mg',
    category: 'Neurology',
    description: 'Nerve pain medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Pregabalin',
    brand: 'Generic',
    dosage: '75mg',
    category: 'Neurology',
    description: 'Nerve pain medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Levetiracetam',
    brand: 'Generic',
    dosage: '500mg',
    category: 'Neurology',
    description: 'Anticonvulsant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Carbamazepine',
    brand: 'Generic',
    dosage: '200mg',
    category: 'Neurology',
    description: 'Anticonvulsant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Topiramate',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Neurology',
    description: 'Anticonvulsant and migraine preventer.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Sumatriptan',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Neurology',
    description: 'Migraine medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Allopurinol',
    brand: 'Generic',
    dosage: '100mg',
    category: 'Rheumatology',
    description: 'Gout medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Colchicine',
    brand: 'Generic',
    dosage: '0.5mg',
    category: 'Rheumatology',
    description: 'Gout medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Methotrexate',
    brand: 'Generic',
    dosage: '2.5mg',
    category: 'Rheumatology',
    description: 'Immunosuppressant.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Hydroxychloroquine',
    brand: 'Generic',
    dosage: '200mg',
    category: 'Rheumatology',
    description: 'DMARD.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Prednisolone',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Steroids',
    description: 'Corticosteroid.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Dexamethasone',
    brand: 'Generic',
    dosage: '0.5mg',
    category: 'Steroids',
    description: 'Corticosteroid.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Methylprednisolone',
    brand: 'Generic',
    dosage: '4mg',
    category: 'Steroids',
    description: 'Corticosteroid.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Sildenafil',
    brand: 'Generic',
    dosage: '50mg',
    category: 'Urology',
    description: 'ED medication.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Tamsulosin',
    brand: 'Generic',
    dosage: '0.4mg',
    category: 'Urology',
    description: 'Alpha blocker for enlarged prostate.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  },
  {
    name: 'Finasteride',
    brand: 'Generic',
    dosage: '5mg',
    category: 'Urology',
    description: '5-alpha reductase inhibitor.',
    prescriptionRequired: true,
    manufacturer: 'Generic',
  }
];

const seedMedicines = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      console.error('Missing MONGODB_URI in env');
      process.exit(1);
    }
    
    await mongoose.connect(mongoUri);
    console.log('Connected to MongoDB.');

    // Find an admin user to own these medicines
    const adminUser = await User.findOne({ role: 'ADMIN' });
    
    if (!adminUser) {
      console.error('No ADMIN user found in the database. Please create one first before seeding medicines.');
      process.exit(1);
    }

    console.log(`Found Admin User: ${adminUser.email}`);

    // Clear existing
    await Medicine.deleteMany({});
    console.log('Cleared existing medicines.');

    const medicinesToInsert = sampleMedicines.map(med => ({
      ...med,
      createdBy: adminUser._id,
    }));

    await Medicine.insertMany(medicinesToInsert);
    console.log(`Successfully seeded ${medicinesToInsert.length} medicines.`);
    process.exit(0);
  } catch (error) {
    console.error('Error seeding medicines:', error);
    process.exit(1);
  }
};

seedMedicines();
